### ISSUE TITLE
Чистота кода

### ISSUE THREAD

**Issue by maked0n** [ftvkyo2011-study/pt-task02#1]
Здесь и в аналогичных местах излишнее копирование
https://github.com/ftvkyo2011-study/pt-task02/blob/b1bb356440a8550b04ebe48701dd338bf080d752/src/pizza.cpp#L91

**Comment by ftvkyo2011** [comment]
@maked0n , вы имеете в виду излишнее копирование данных?
В таком случае, корректно ли будет хранить ссылку на данные, как мы храним пиццамейкера в кухне? Я предполагал, что на каждую кастомную пиццу надо делать нового пиццамейкера, а не изменять существующих.

//Знаю, заодно перенести инициализацию кастомного пиццамейкера из конструктора в сеттеры.

**Comment by maked0n** [comment]
да, излишнее: ti и to нужно передать по ссылке на константный объект
