### ISSUE TITLE
Польза паттерна Builder

### ISSUE THREAD

**Issue by maked0n** [ftvkyo2011-study/pt-task02#3]
Зачем для такого объекта использовать паттерн Builder?
https://github.com/ftvkyo2011-study/pt-task02/blob/b1bb356440a8550b04ebe48701dd338bf080d752/include/pt-task02/pizza.hpp#L10

**Comment by ftvkyo2011** [comment]
@maked0n , предположу, что ваш вопрос ставит цель проверить меня, а не намекает, что для пиццы неадекватно использовать Builder. Напишите, если это не так.

1. Реализация абстрактной фабрики для всех возможных комбинаций теста (n штук) и топпингов (m штук) потребовала бы написания n*m абстрактных фабрик, если я правильно понял суть паттерна, а это, как минимум, больно.
2. Builder позволяет создавать единственный дополнительный класс на каждый новый тип пиццы, что довольно удобно - изменения можно вносить только в одном месте (+ обновить header). К тому же довольно удобно реализовать кастомного пиццамейкера, чтоб на сайте повесить красивенький конструктор пицц. При этом, как мне кажется, будет красиво дать возможность пользователю сохранять этого кастомного пиццамейкера в личном кабинете, получится типа "Code as data", чтоб он мог хранить избранные пиццы.

Единственное, получается, будто на каждую пиццу требуется свой "работник пиццерии", но мои пиццамейкеры вроде как !=персоналу кухни.

**Comment by ftvkyo2011** [comment]
Я понял, вы, вероятно, хотите, чтобы `IPizzaMaker` были `friend` для `CPizza` и настраивали его приватные поля. Сейчас исправлю.
